TRUNCATE TABLE `wk_ad`;
INSERT INTO `wk_ad` VALUES ('1', '头部960x90巨幅广告', '<!-- 头部960x90巨幅广告 -->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/950x90.gif\" style=\"width:960px;height:90px\"/>', '1361849319', '1', '1');
INSERT INTO `wk_ad` VALUES ('2', '文章页640x60', '<!--文章页640x60-->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/640x60.gif\"/>', '1361849373', '1', '1');
INSERT INTO `wk_ad` VALUES ('3', '通用250x250', '<!--通用250x250-->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/250x250.gif\"/>', '1361849423', '1', '1');
INSERT INTO `wk_ad` VALUES ('4', '通用728x90广告', '<!--通用728x90 广告-->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/728x90.gif\"/>', '1361849471', '1', '1');
INSERT INTO `wk_ad` VALUES ('5', '468x60banner广告', '<!-- 468x60banner广告 -->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/468X60.gif\"/>', '1361849704', '1', '1');
INSERT INTO `wk_ad` VALUES ('6', '120x60广告位', '<!--120x60广告位 -->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/120x60.gif\"/>', '1361849838', '1', '1');
INSERT INTO `wk_ad` VALUES ('7', '250x60 广告位', '<!--250x60 广告位-->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/250x60.gif\"/>', '1361850919', '1', '1');
INSERT INTO `wk_ad` VALUES ('8', '300x250广告位', '<!--300x250广告位 -->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/300x250.gif\"/>', '1361851102', '1', '1');
INSERT INTO `wk_ad` VALUES ('9', '200x200广告位', '<!--200x200广告位-->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/200x200.gif\"/>', '1361851286', '1', '1');
INSERT INTO `wk_ad` VALUES ('10', '250x300广告位', '<!-- 250x300广告位 -->\r\n<img src=\"http://oss.aliyuncs.com/waikucms/ad/250x300.gif\"/>', '1361859186', '1', '1');
TRUNCATE TABLE `wk_ad_group`;
INSERT INTO `wk_ad_group` VALUES ('1', '默认分类');
TRUNCATE TABLE `wk_addonarticle`;
TRUNCATE TABLE `wk_addondiybg`;
INSERT INTO `wk_addondiybg` VALUES ('57', '15', '', '/waiku/Public/Uploads/file/20140810/87f349c5.swf', '/waiku/Public/Uploads/image/20140810/7324e1af.jpg');
INSERT INTO `wk_addondiybg` VALUES ('58', '15', '', '/waiku/Public/Uploads/file/20140810/9d57df19.swf', '/waiku/Public/Uploads/image/20140810/71a02d3a.jpg');
INSERT INTO `wk_addondiybg` VALUES ('59', '15', '', '/waiku/Public/Uploads/file/20140810/d71fa42c.swf', '/waiku/Public/Uploads/image/20140810/2b651720.jpg');
TRUNCATE TABLE `wk_addondiyinfo`;
INSERT INTO `wk_addondiyinfo` VALUES ('63', '19', '', '信息简介', '信息内容', '/waiku/Public/Uploads/image/20140811/cde66a72.jpg', '', '1', '/waiku/Public/Uploads/image/20140811/ad685e37.jpg', '', '');
INSERT INTO `wk_addondiyinfo` VALUES ('65', '19', '', '信息简介信息简介信息简介信息简介2', '信息内容信息内容信息内容2', '/waiku/Public/Uploads/image/20140813/cde66a72.jpg', '', '1', '/waiku/Public/Uploads/image/20140813/ad685e37.jpg', '590', '330');
INSERT INTO `wk_addondiyinfo` VALUES ('72', '19', '', '水电费水电费', '水电费问任务而为人45 3453&nbsp;', '/waiku/Public/Uploads/image/20140818/cde66a72.jpg', '', '1', '/waiku/Public/Uploads/image/20140818/ad685e37.jpg', '', '');
INSERT INTO `wk_addondiyinfo` VALUES ('73', '36', '', '', '阿里巴巴集团主要创始人之一、阿里巴巴集团主席和首席执行官、阿里巴巴公司主席和非执行董事、软银集团董事、中国雅虎董事局主席、亚太经济合作组织（APEC）下工商咨询委员会(ABAC)会员。<br />\r\n<a target=\"_blank\" href=\"http://www.taobao.com\">http://www.taobao.com</a>', '', 'http://www.qq.com', '', '/waiku/Public/Uploads/image/20140819/b9916d8c.jpg', '', '');
INSERT INTO `wk_addondiyinfo` VALUES ('74', '36', '', '', '2005年8月，百度<font color=\"#E53333\"><b>在美国纳斯达克</b></font>成功上市，成<font style=\"background-color:#E53333;\">为全球资本市场最</font>受关注的上市公司之一。在李彦宏领导下，百度不仅拥有全球最优秀的搜索引擎技术团队，同时<font face=\"Microsoft YaHei\" size=\"24\">也拥有国内最</font>优秀的管理团队、产品设计、开发和维<font size=\"5\">护团队；在商业</font>模式方面，也同样具有开创性。<br />\r\n<a target=\"_blank\" href=\"http://www.baidu.com\">http://www.baidu.com</a>', '', 'http://www.baidu.com', '', '/waiku/Public/Uploads/image/20140819/70768418.jpg', '', '');
INSERT INTO `wk_addondiyinfo` VALUES ('75', '37', '', '', '微软全球渠道主管Allison Watson', '', '', '', '/waiku/Public/Uploads/image/20140819/42d33027.jpg', '', '');
INSERT INTO `wk_addondiyinfo` VALUES ('76', '37', '', '', '赛门铁克CEO约翰·汤普森', '', '', '', '/waiku/Public/Uploads/image/20140819/4367155f.jpg', '', '');
TRUNCATE TABLE `wk_addondiyintro`;
INSERT INTO `wk_addondiyintro` VALUES ('64', '20', '', '简介内容', '/waiku/Public/Uploads/image/20140811/6d26bada.jpg');
INSERT INTO `wk_addondiyintro` VALUES ('77', '39', '', '文本展示啊', '/waiku/Public/Uploads/image/20140811/6d26bada.jpg');
TRUNCATE TABLE `wk_addondiymusic`;
INSERT INTO `wk_addondiymusic` VALUES ('60', '16', '', 'http://120.198.238.86/rm.sina.com.cn/wm/VZ200911231412336707VK/music/MUSIC0912012038567601.mp3', '/waiku/Public/Uploads/image/20140810/fbbd3ba1.jpg', '');
TRUNCATE TABLE `wk_addondiyphoto`;
INSERT INTO `wk_addondiyphoto` VALUES ('62', '18', '', '四点多风格的双方各', '/waiku/Public/Uploads/image/20140811/772c0db9.jpg', '', '/waiku/Public/Uploads/image/20140811/9b09b3a2.jpg');
INSERT INTO `wk_addondiyphoto` VALUES ('66', '18', '', '图片内容阿斯顿发生地方', '/waiku/Public/Uploads/image/20140816/52145360.jpg', '', '/waiku/Public/Uploads/image/20140816/81b12ce9.jpg');
INSERT INTO `wk_addondiyphoto` VALUES ('67', '27', '', 'uhnsha摄影包体1111', '/waiku/Public/Uploads/image/20140816/df724086.jpg', '', '/waiku/Public/Uploads/image/20140816/3679a5a8.jpg');
INSERT INTO `wk_addondiyphoto` VALUES ('68', '27', '', '婚纱摄影2婚纱摄影2婚纱摄影2', '/waiku/Public/Uploads/image/20140816/e0577433.jpg', '', '/waiku/Public/Uploads/image/20140816/403f4c4e.jpg');
INSERT INTO `wk_addondiyphoto` VALUES ('69', '28', '', '风景摄影1风景摄影1风景摄影1', '/waiku/Public/Uploads/image/20140816/772c0db9.jpg', '', '/waiku/Public/Uploads/image/20140816/9b09b3a2.jpg');
INSERT INTO `wk_addondiyphoto` VALUES ('70', '28', '', '风景摄影2风景摄影2风景摄影2', '/waiku/Public/Uploads/image/20140816/df724086.jpg', '', '/waiku/Public/Uploads/image/20140816/3679a5a8.jpg');
TRUNCATE TABLE `wk_addondiyvideo`;
INSERT INTO `wk_addondiyvideo` VALUES ('61', '32', '', '/waiku/Public/Uploads/image/20140816/9b09b3a2.jpg', '540', '360', '/waiku/Public/Uploads/file/20140811/d76e33e9.flv', '斯蒂芬斯蒂芬斯蒂芬', '水水水水水水水水水水水水', '');
INSERT INTO `wk_addondiyvideo` VALUES ('71', '17', '', '/waiku/Public/Uploads/image/20140816/c7d77080.jpg', '720', '480', '/waiku/Public/Uploads/file/20140811/d76e33e9.flv', '视频描述', '视频内容', '');
TRUNCATE TABLE `wk_addondownload`;
TRUNCATE TABLE `wk_addonjob`;
TRUNCATE TABLE `wk_admin`;
INSERT INTO `wk_admin` VALUES ('1', 'admin', 'c2d4101a4f67fbed957d260ff0f26a17', '1409586139', '127.0.0.1', '超级');
TRUNCATE TABLE `wk_archive`;
INSERT INTO `wk_archive` VALUES ('66', '18', '', '9', '1', '197', '20', '图片标题2', '', '', '不详', '网络', '', '1408203528', '1408203528', '1', '', '图片内容阿斯顿发生地方...', '0');
INSERT INTO `wk_archive` VALUES ('67', '27', '', '9', '1', '143', '20', '婚纱摄影标题1', '', '', '不详', '网络', '', '1408203661', '1408203661', '1', '', 'uhnsha摄影包体1111...', '0');
INSERT INTO `wk_archive` VALUES ('68', '27', '', '9', '1', '107', '20', '婚纱摄影2', '', '', '不详', '网络', '', '1408203783', '1408203783', '1', '', '婚纱摄影2婚纱摄影2婚纱摄影2...', '0');
INSERT INTO `wk_archive` VALUES ('69', '28', '', '9', '1', '147', '20', '风景摄影1', '', '', '不详', '网络', '', '1408203974', '1408203974', '1', '', '风景摄影1风景摄影1风景摄影1...', '0');
INSERT INTO `wk_archive` VALUES ('70', '28', '', '9', '1', '192', '20', '风景摄影2', '', '', '不详', '网络', '', '1408204016', '1408204016', '1', '', '风景摄影2风景摄影2风景摄影2...', '0');
INSERT INTO `wk_archive` VALUES ('71', '17', '', '8', '1', '83', '20', '视频', '', '', '不详', '网络', '', '1408278300', '1408278300', '1', '', '视频内容...', '0');
INSERT INTO `wk_archive` VALUES ('72', '19', '', '10', '1', '188', '20', '信息3', '', '', '不详', '网络', '', '1408370309', '1408370309', '1', '', '水电费问任务而为人45 3453&nbsp;...', '0');
INSERT INTO `wk_archive` VALUES ('73', '36', '', '10', '1', '81', '20', '马云', '', '', '不详', '网络', '', '1408464303', '1408464303', '1', '', '阿里巴巴集团主要创始人之一、阿里巴巴集团主席和首席执行官、阿里巴巴公司主席和非执行董事、软银集团董事、中国雅虎董事局主席、亚太经济合作组织（APEC）下工商咨询委员会(ABAC)会员。\r\nhttp://www.taobao.com...', '0');
INSERT INTO `wk_archive` VALUES ('74', '36', '', '10', '1', '80', '20', '李彦宏', '', '', '不详', '网络', '', '1408464457', '1408464457', '1', '', '2005年8月，百度在美国纳斯达克成功上市，成为全球资本市场最受关注的上市公司之一。在李彦宏领导下，百度不仅拥有全球最优秀的搜索引擎技术团队，同时也拥有国内最优秀的管理团队、产品设计、开发和维护团队；在商业模式方面，也同样具有开创性，对中国企业分享互联网成果起到了积极推动作用。\r\nhttp://www.baidu.com...', '0');
INSERT INTO `wk_archive` VALUES ('75', '37', '', '10', '1', '192', '20', '微软全球渠道主管Allison Watson', '', '', '不详', '网络', '', '1408464523', '1408464523', '1', '', '微软全球渠道主管Allison Watson...', '0');
INSERT INTO `wk_archive` VALUES ('76', '37', '', '10', '1', '69', '20', '赛门铁克CEO约翰·汤普森', '', '', '不详', '网络', '', '1408464576', '1408464576', '1', '', '赛门铁克CEO约翰·汤普森...', '0');
INSERT INTO `wk_archive` VALUES ('77', '39', '', '11', '1', '72', '20', '文本展示a', '', '', '不详', '网络', '', '1408467397', '1408467397', '1', '', '文本展示啊...', '0');
INSERT INTO `wk_archive` VALUES ('56', '13', '', '5', '1', '105', '20', '幻灯测试3', '', '', '不详', '网络', '', '1390119188', '1390119188', '1', '', '幻灯描述...', '0');
INSERT INTO `wk_archive` VALUES ('57', '15', '', '6', '1', '98', '20', '背景1', '', '', '不详', '网络', '', '1407678777', '1407678777', '1', '', '...', '0');
INSERT INTO `wk_archive` VALUES ('58', '15', '', '6', '1', '170', '20', '背景2', '', '', '不详', '网络', '', '1407682653', '1407682653', '1', '', '...', '0');
INSERT INTO `wk_archive` VALUES ('59', '15', '', '6', '1', '185', '20', '背景3', '', '', '不详', '网络', '', '1409468602', '1407682695', '1', '', '...', '0');
INSERT INTO `wk_archive` VALUES ('60', '16', '', '7', '1', '170', '20', '音乐1', '', '', '不详', '网络', '', '1407682829', '1407682829', '1', '', '...', '0');
INSERT INTO `wk_archive` VALUES ('61', '32', '', '8', '1', '159', '20', '视频合辑1视频1', '', '', '不详', '网络', '', '1407770727', '1407770727', '1', '', '水水水水水水水水水水水水...', '0');
INSERT INTO `wk_archive` VALUES ('62', '18', '', '9', '1', '67', '20', '图片1', '', '', '不详', '网络', '', '1407771080', '1407771080', '1', '', '四点多风格的双方各...', '0');
INSERT INTO `wk_archive` VALUES ('63', '19', '', '10', '1', '176', '20', '信息1', '', '', '不详', '网络', '', '1407771582', '1407771582', '1', '', '信息内容...', '0');
INSERT INTO `wk_archive` VALUES ('64', '20', '', '11', '1', '88', '20', '简介1', '', '', '不详', '网络', '', '1407771675', '1407771675', '1', '', '简介内容...', '0');
INSERT INTO `wk_archive` VALUES ('65', '19', '', '10', '1', '67', '20', '信息2', '', '', '不详', '网络', '', '1407944150', '1407944150', '1', '', '信息内容信息内容信息内容2...', '0');
INSERT INTO `wk_archive` VALUES ('54', '13', '', '5', '1', '76', '20', '幻灯标题测试1', '', '', '不详', '网络', '', '1390119128', '1390119128', '1', '', '幻灯描述啊发生的发生法斯蒂芬...', '0');
INSERT INTO `wk_archive` VALUES ('55', '13', '', '5', '1', '128', '20', '幻灯测试2', '', '', '不详', '网络', '', '1390119166', '1390119166', '1', '', '换的呢过面桑德菲杰...', '0');
TRUNCATE TABLE `wk_arcmodel`;
INSERT INTO `wk_arcmodel` VALUES ('1', 'article', '文章', '文章标题', '<fieldset>\r\n<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field name=\"body\" tag=\"editor\" id=\"Content\" group=\"basic\" style\r\n=\"width:800px;height:300px;\" alt=\"正文内容\"/>\r\n</fieldset>', 'addonarticle', '0', '0');
INSERT INTO `wk_arcmodel` VALUES ('2', 'download', '下载', '下载标题', '<fieldset>\r\n<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field name=\"soft_author\" tag=\"input\" type=\"text\"  id=\"soft_author\" size=\"20\" group=\"basic\" alt=\"软件作者\" value=\'匿名\'/>\r\n<field name=\"soft_nature\" tag=\"radio\"  id=\"soft_nature\" value=\'授权免费,开源软件,共享软件,商业软件\' group=\"basic\" alt=\"软件性质\"/>\r\n<field name=\"soft_version\" tag=\"input\" type=\"text\"  id=\"soft_version\" size=\"20\" group=\"basic\" alt=\"软件版本\" value=\'1.0\'/>\r\n<field name=\"soft_lang\" tag=\"select\"  id=\"soft_nature\" value=\'简体中文,繁体中文,英文,多国语\'  group=\"basic\" alt=\"软件语言\"/>\r\n<field name=\"soft_platform\" tag=\"checkbox\" id=\"soft_platform\" value=\'xp,win2003,vista,win7,win8,linux,unix\' group=\"basic\" alt=\"软件平台\" src=\"./Public/Model/download/selectall.html\"/>\r\n<field name=\"soft_size\" tag=\"input\" type=\"text\"  id=\"soft_size\" size=\"20\" group=\"basic\" alt=\"软件大小（KB）\" value=\'0\'/>\r\n<field name=\"soft_contact\" tag=\"input\" type=\"text\"  id=\"soft_contact\" size=\"20\" group=\"basic\" alt=\"联系人\" value=\'暂无\'/>\r\n<field name=\"soft_downloadnum\" tag=\"input\" type=\"text\"  id=\"soft_downloadnum\" size=\"20\" group=\"basic\" alt=\"下载次数\" value=\'1\' src=\"./Public/Model/download/upload.html\"/>\r\n<field name=\"downloadurl\" tag=\"textarea\"  id=\"downloadurl\" group=\"basic\" style=\"width:800px;height:100px;\" alt=\"下载地址（多个地址请换行）\"/>\r\n<field name=\"body\" tag=\"editor\" id=\"Content\" group=\"basic\" style=\"width:800px;height:300px;\" alt=\"下载介绍\" src=\"./Public/Model/download/docheck.html\"/>\r\n</fieldset>', 'addondownload', '1', '1');
INSERT INTO `wk_arcmodel` VALUES ('3', 'job', '招聘', '招聘标题', '<fieldset>\r\n<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field name=\"job_num\" tag=\"input\" type=\"text\"  id=\"job_num\" size=\"20\" group=\"basic\" alt=\"招聘人数\" value=\'1\'/>\r\n<field name=\"job_money\" tag=\"input\"  size=\'50\' id=\"job_money\" value=\'面议\'  group=\"basic\" alt=\"工作薪水\"/>\r\n<field name=\"job_lang\" tag=\"input\"  id=\"job_lang\" value=\'不限\' group=\"basic\" alt=\"语言要求\" size=\'50\'/>\r\n<field name=\"job_degree\" tag=\"radio\" type=\"text\"  id=\"job_degree\"  group=\"basic\" alt=\"学历要求\" value=\'不限,小学,初中,高中,中专,大专,专科,本科,硕士,博士,博士后\'/>\r\n<field name=\"job_job\" tag=\"input\"  size=\'50\' id=\"job_job\" value=\'干事\'  group=\"basic\" alt=\"职位职能\"/>\r\n<field name=\"job_year\" tag=\"radio\" id=\"job_year\" value=\'不限,半年,一年,两年,三年,四年,五年\' group=\"basic\" alt=\"工作年限\" />\r\n<field name=\"body\" tag=\"editor\" id=\"Content\" group=\"basic\" style=\"width:800px;height:300px;\" alt=\"职位详细描述\" />\r\n</fieldset>', 'addonjob', '1', '1');
INSERT INTO `wk_arcmodel` VALUES ('5', 'slide', '幻灯', '幻灯标题', '<fieldset>		<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field tag=\'editor\' group=\'basic\' name=\'body\' id=\'body\' value=\'\' alt=\'幻灯描述\'  style=\"width:800px;height:300px;\"/>\r\n<field tag=\'insertpic\' group=\'basic\' name=\'slideurl\' id=\'slideurl\' value=\'\' alt=\'幻灯图\' />\r\n</fieldset>', 'addonslide', '1', '0');
INSERT INTO `wk_arcmodel` VALUES ('6', 'diybg', '背景', '背景标题', '<fieldset>		<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field tag=\'insertfile\' group=\'basic\' name=\'url\' id=\'url\' value=\'\' alt=\'背景地址\' />\r\n<field tag=\'insertpic\' group=\'basic\' name=\'img\' id=\'img\' value=\'\' alt=\'背景缩略图\' />\r\n</fieldset>', 'addondiybg', '1', '0');
INSERT INTO `wk_arcmodel` VALUES ('7', 'diymusic', '音乐', '音乐标题', '<fieldset>		<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field tag=\'insertfile\' group=\'basic\' name=\'url\' id=\'url\' value=\'\' alt=\'音乐地址\' />\r\n<field tag=\'insertpic\' group=\'basic\' name=\'pic\' id=\'pic\' value=\'\' alt=\'音乐缩略图\' />\r\n<field tag=\'inserturl\' group=\'basic\' name=\'link\' id=\'link\' value=\'\' alt=\'下载地址\' />\r\n</fieldset>', 'addondiymusic', '1', '0');
INSERT INTO `wk_arcmodel` VALUES ('8', 'diyvideo', '视频', '视频标题', '<fieldset>		<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field tag=\'insertpic\' group=\'basic\' name=\'img\' id=\'img\' value=\'\' alt=\'视频缩略图\' />\r\n<field tag=\'input\' group=\'basic\' name=\'width\' id=\'width\' value=\'\' alt=\'视频宽度\'  size=\"45\"/>\r\n<field tag=\'input\' group=\'basic\' name=\'height\' id=\'height\' value=\'\' alt=\'视频高度\'  size=\"45\"/>\r\n<field tag=\'insertfile\' group=\'basic\' name=\'video\' id=\'video\' value=\'\' alt=\'视频地址\' />\r\n<field tag=\'editor\' group=\'basic\' name=\'topic\' id=\'topic\' value=\'\' alt=\'视频描述\'  style=\"width:800px;height:300px;\"/>\r\n<field tag=\'editor\' group=\'basic\' name=\'body\' id=\'body\' value=\'\' alt=\'视频内容\'  style=\"width:800px;height:300px;\"/>\r\n<field tag=\'inserturl\' group=\'basic\' name=\'url\' id=\'url\' value=\'\' alt=\'跳转地址\' />\r\n</fieldset>', 'addondiyvideo', '1', '0');
INSERT INTO `wk_arcmodel` VALUES ('9', 'diyphoto', '图片', '图片标题', '<fieldset>		<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field tag=\'editor\' group=\'basic\' name=\'body\' id=\'body\' value=\'\' alt=\'图片内容\'  style=\"width:800px;height:300px;\"/>\r\n<field tag=\'insertpic\' group=\'basic\' name=\'pic\' id=\'pic\' value=\'\' alt=\'图片\' />\r\n<field tag=\'inserturl\' group=\'basic\' name=\'url\' id=\'url\' value=\'\' alt=\'图片链接\' />\r\n<field tag=\'insertpic\' group=\'basic\' name=\'spic\' id=\'spic\' value=\'\' alt=\'图片缩略图\' />\r\n</fieldset>', 'addondiyphoto', '1', '0');
INSERT INTO `wk_arcmodel` VALUES ('10', 'diyinfo', '信息', '信息标题', '<fieldset>		<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field tag=\'editor\' group=\'basic\' name=\'topic\' id=\'topic\' theme=\'simple\' value=\'\' alt=\'信息简介\'  style=\"width:800px;height:300px;\"/>\r\n<field tag=\'editor\' group=\'basic\' name=\'body\' id=\'body\' theme=\'simple\' value=\'\' alt=\'信息内容\'  style=\"width:800px;height:300px;\"/>\r\n<field tag=\'insertpic\' group=\'basic\' name=\'simg\' id=\'simg\' value=\'\' alt=\'信息缩略图\' />\r\n<field tag=\'input\' group=\'basic\' name=\'url\' id=\'url\' value=\'\' alt=\'跳转链接\'  size=\"45\"/>\r\n<field tag=\'input\' group=\'basic\' name=\'open\' id=\'open\' value=\'\' alt=\'信息打开方式\'  size=\"45\"/>\r\n<field tag=\'insertpic\' group=\'basic\' name=\'img\' id=\'img\' value=\'\' alt=\'信息图片\' />\r\n<field tag=\'input\' group=\'basic\' name=\'ywidth\' id=\'ywidth\' value=\'\' alt=\'信息宽度\'  size=\"45\"/>\r\n<field tag=\'input\' group=\'basic\' name=\'yheight\' id=\'yheight\' value=\'\' alt=\'信息宽度\'  size=\"45\"/>\r\n</fieldset>', 'addondiyinfo', '1', '0');
INSERT INTO `wk_arcmodel` VALUES ('11', 'diyintro', '简介', '简介标题', '<fieldset>		<field name=\"redirecturl\" tag=\"input\" type=\"text\"  id=\"redirecturl\" size=\"50\" group=\"basic\" alt=\"跳转地址\"/>\r\n<field tag=\'editor\' group=\'basic\' name=\'body\' id=\'body\' value=\'\' alt=\'简介内容\'  style=\"width:800px;height:300px;\"/>\r\n<field tag=\'insertpic\' group=\'basic\' name=\'pic\' id=\'pic\' value=\'\' alt=\'简介缩略图\' />\r\n</fieldset>', 'addondiyintro', '1', '0');
TRUNCATE TABLE `wk_arctiny`;
INSERT INTO `wk_arctiny` VALUES ('66', '18', '9', '1408203528', '1');
INSERT INTO `wk_arctiny` VALUES ('67', '27', '9', '1408203661', '1');
INSERT INTO `wk_arctiny` VALUES ('68', '27', '9', '1408203783', '1');
INSERT INTO `wk_arctiny` VALUES ('69', '28', '9', '1408203974', '1');
INSERT INTO `wk_arctiny` VALUES ('70', '28', '9', '1408204016', '1');
INSERT INTO `wk_arctiny` VALUES ('71', '17', '8', '1408278300', '1');
INSERT INTO `wk_arctiny` VALUES ('72', '19', '10', '1408370309', '1');
INSERT INTO `wk_arctiny` VALUES ('73', '36', '10', '1408464303', '1');
INSERT INTO `wk_arctiny` VALUES ('74', '36', '10', '1408464457', '1');
INSERT INTO `wk_arctiny` VALUES ('75', '37', '10', '1408464523', '1');
INSERT INTO `wk_arctiny` VALUES ('76', '37', '10', '1408464576', '1');
INSERT INTO `wk_arctiny` VALUES ('77', '39', '11', '1408467397', '1');
INSERT INTO `wk_arctiny` VALUES ('55', '13', '5', '1390119166', '1');
INSERT INTO `wk_arctiny` VALUES ('56', '13', '5', '1390119188', '1');
INSERT INTO `wk_arctiny` VALUES ('57', '15', '6', '1407678777', '1');
INSERT INTO `wk_arctiny` VALUES ('58', '15', '6', '1407682653', '1');
INSERT INTO `wk_arctiny` VALUES ('59', '15', '6', '1407682695', '1');
INSERT INTO `wk_arctiny` VALUES ('60', '16', '7', '1407682829', '1');
INSERT INTO `wk_arctiny` VALUES ('61', '32', '8', '1407770727', '1');
INSERT INTO `wk_arctiny` VALUES ('62', '18', '9', '1407771080', '1');
INSERT INTO `wk_arctiny` VALUES ('54', '13', '5', '1390119128', '1');
INSERT INTO `wk_arctiny` VALUES ('63', '19', '10', '1407771582', '1');
INSERT INTO `wk_arctiny` VALUES ('64', '20', '11', '1407771675', '1');
INSERT INTO `wk_arctiny` VALUES ('65', '19', '10', '1407944150', '1');
TRUNCATE TABLE `wk_arctype`;
INSERT INTO `wk_arctype` VALUES ('15', '6', '0', '', '背景', '', '', '', '', '50', '0', '0', '{style}/index_diybg.htm', '{style}/list_diybg.htm', '{style}/article_diybg.htm', '{wapstyle}/index_diybg.htm', '{wapstyle}/list_diybg.htm', '{wapstyle}/article_diybg.htm', '1', '');
INSERT INTO `wk_arctype` VALUES ('13', '5', '0', '', '首页幻灯', 'slide', '_a', '', '', '1', '0', '0', '{style}/index_slide.htm', '{style}/list_slide.htm', '{style}/article_slide.htm', '{wapstyle}/index_slide.htm', '{wapstyle}/list_slide.htm', '{wapstyle}/article_slide.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('16', '7', '0', '', '背景音乐', '', '', '', '', '50', '0', '0', '{style}/index_diymusic.htm', '{style}/list_diymusic.htm', '{style}/article_diymusic.htm', '{wapstyle}/index_diymusic.htm', '{wapstyle}/list_diymusic.htm', '{wapstyle}/article_diymusic.htm', '1', '');
INSERT INTO `wk_arctype` VALUES ('17', '8', '0', '', '视频演示', 'player', '_a', '', '', '6', '0', '0', '{style}/index_diyvideo.htm', '{style}/videomain.htm', '{style}/article_diyvideo.htm', '{wapstyle}/index_diyvideo.htm', '{wapstyle}/list_diyvideo.htm', '{wapstyle}/article_diyvideo.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('18', '9', '0', '', '最新图片', 'photo', '_c', '', '', '4', '0', '0', '{style}/index_diyphoto.htm', '{style}/list_diyphoto.htm', '{style}/article_diyphoto.htm', '{wapstyle}/index_diyphoto.htm', '{wapstyle}/list_diyphoto.htm', '{wapstyle}/article_diyphoto.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('19', '10', '0', '', '信息演示', 'news', '_a', '', '', '3', '0', '0', '{style}/index_diyinfo.htm', '{style}/list_diyinfo.htm', '{style}/article_diyinfo.htm', '{wapstyle}/index_diyinfo.htm', '{wapstyle}/list_diyinfo.htm', '{wapstyle}/article_diyinfo.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('20', '11', '0', '', '简介演示', 'text', '_c', '', '', '2', '0', '0', '{style}/index_diyintro.htm', '{style}/list_diyintro.htm', '{style}/article_diyintro.htm', '{wapstyle}/index_diyintro.htm', '{wapstyle}/list_diyintro.htm', '{wapstyle}/article_diyintro.htm', '4', '');
INSERT INTO `wk_arctype` VALUES ('26', '9', '0', '', '相册展示', 'photo', '_a', '', '', '5', '0', '0', '{style}/index_diyphoto.htm', '{style}/photolist.htm', '{style}/article_diyphoto.htm', '{wapstyle}/index_diyphoto.htm', '{wapstyle}/list_diyphoto.htm', '{wapstyle}/article_diyphoto.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('25', '2', '0', '', 'contant', 'contact', '', '', '联系我们的内容', '10', '0', '0', '{style}/index_download.htm', '{style}/list_download.htm', '{style}/article_download.htm', '{wapstyle}/index_download.htm', '{wapstyle}/list_download.htm', '{wapstyle}/article_download.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('27', '9', '0', '', '婚纱摄影', 'photo', '_b', 'sdfsdfsdf', '', '50', '26', '0-26', '{style}/index_diyphoto.htm', '{style}/list_diyphoto.htm', '{style}/article_diyphoto.htm', '{wapstyle}/index_diyphoto.htm', '{wapstyle}/list_diyphoto.htm', '{wapstyle}/article_diyphoto.htm', '0', '/waiku/Public/Uploads/image/20140816/e0697a3b.jpg');
INSERT INTO `wk_arctype` VALUES ('28', '9', '0', '', '风景摄影', 'photo', '_a', '分类2的简介', '', '50', '26', '0-26', '{style}/index_diyphoto.htm', '{style}/list_diyphoto.htm', '{style}/article_diyphoto.htm', '{wapstyle}/index_diyphoto.htm', '{wapstyle}/list_diyphoto.htm', '{wapstyle}/article_diyphoto.htm', '0', '/waiku/Public/Uploads/image/20140816/c7d77080.jpg');
INSERT INTO `wk_arctype` VALUES ('31', '8', '0', '', '视频合辑', 'player', '_b', '', '', '7', '0', '0', '{style}/index_diyvideo.htm', '{style}/videolist.htm', '{style}/article_diyvideo.htm', '{wapstyle}/index_diyvideo.htm', '{wapstyle}/list_diyvideo.htm', '{wapstyle}/article_diyvideo.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('32', '8', '0', '', '视频合辑1', '', '', '', '', '50', '31', '0-31', '{style}/index_diyvideo.htm', '{style}/list_diyvideo.htm', '{style}/article_diyvideo.htm', '{wapstyle}/index_diyvideo.htm', '{wapstyle}/list_diyvideo.htm', '{wapstyle}/article_diyvideo.htm', '1', '');
INSERT INTO `wk_arctype` VALUES ('33', '8', '0', '', '视频合辑2', '', '', '', '', '50', '31', '0-31', '{style}/index_diyvideo.htm', '{style}/list_diyvideo.htm', '{style}/article_diyvideo.htm', '{wapstyle}/index_diyvideo.htm', '{wapstyle}/list_diyvideo.htm', '{wapstyle}/article_diyvideo.htm', '1', '');
INSERT INTO `wk_arctype` VALUES ('35', '10', '0', '', '团队介绍', 'news', '_b', '', '', '8', '0', '0', '{style}/index_diyinfo.htm', '{style}/list_team.htm', '{style}/article_diyinfo.htm', '{wapstyle}/index_diyinfo.htm', '{wapstyle}/list_diyinfo.htm', '{wapstyle}/article_diyinfo.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('36', '10', '0', '', '国内IT', '', '', '', '', '50', '35', '0-35', '{style}/index_diyinfo.htm', '{style}/list_diyinfo.htm', '{style}/article_diyinfo.htm', '{wapstyle}/index_diyinfo.htm', '{wapstyle}/list_diyinfo.htm', '{wapstyle}/article_diyinfo.htm', '1', '');
INSERT INTO `wk_arctype` VALUES ('37', '10', '0', '', '国外IT', '', '', '', '', '50', '35', '0-35', '{style}/index_diyinfo.htm', '{style}/list_diyinfo.htm', '{style}/article_diyinfo.htm', '{wapstyle}/index_diyinfo.htm', '{wapstyle}/list_diyinfo.htm', '{wapstyle}/article_diyinfo.htm', '1', '');
INSERT INTO `wk_arctype` VALUES ('38', '1', '2', 'http://www.qq.com', '友情链接', '', '', '', '', '11', '0', '0', '{style}/index_article.htm', '{style}/list_article.htm', '{style}/article_article.htm', '{wapstyle}/index_article.htm', '{wapstyle}/list_article.htm', '{wapstyle}/article_article.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('39', '11', '0', '', '文本1', 'text', '_a', '', '', '50', '20', '0-20', '{style}/index_diyintro.htm', '{style}/list_diyintro.htm', '{style}/article_diyintro.htm', '{wapstyle}/index_diyintro.htm', '{wapstyle}/list_diyintro.htm', '{wapstyle}/article_diyintro.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('40', '11', '0', '', '文本2', 'text', '_b', '', '', '50', '20', '0-20', '{style}/index_diyintro.htm', '{style}/list_diyintro.htm', '{style}/article_diyintro.htm', '{wapstyle}/index_diyintro.htm', '{wapstyle}/list_diyintro.htm', '{wapstyle}/article_diyintro.htm', '0', '');
INSERT INTO `wk_arctype` VALUES ('41', '11', '0', '', '文本3', 'text', '_c', '', '', '50', '20', '0-20', '{style}/index_diyintro.htm', '{style}/list_diyintro.htm', '{style}/article_diyintro.htm', '{wapstyle}/index_diyintro.htm', '{wapstyle}/list_diyintro.htm', '{wapstyle}/article_diyintro.htm', '0', '');
TRUNCATE TABLE `wk_articlelink`;
TRUNCATE TABLE `wk_config`;
INSERT INTO `wk_config` VALUES ('1', 'cfg_basehost', '站点根网址：', '1', 'string', 'http://localhost', '');
INSERT INTO `wk_config` VALUES ('2', 'cfg_indexurl', '网页主页链接：', '1', 'string', '/pppon', '');
INSERT INTO `wk_config` VALUES ('3', 'cfg_indexname', '主页链接名：', '1', 'string', '主页', '');
INSERT INTO `wk_config` VALUES ('4', 'cfg_webname', '网站名称：', '1', 'string', '我的测试网站', '');
INSERT INTO `wk_config` VALUES ('5', 'cfg_df_style', '模板默认风格：', '1', 'string', 'default', '');
INSERT INTO `wk_config` VALUES ('6', 'cfg_powerby', '网站版权信息：', '1', 'textarea', 'Copyright &copy; 2011-2013 pppon.com 无界科技 版权所有', '');
INSERT INTO `wk_config` VALUES ('25', 'cfg_html_editor', 'Html编辑器', '3', 'string', 'kindeditor', 'kindeditor');
INSERT INTO `wk_config` VALUES ('7', 'cfg_keywords', '站点默认关键字：', '1', 'string', 'PPPON', '');
INSERT INTO `wk_config` VALUES ('8', 'cfg_description', '站点描述：', '1', 'textarea', '', '');
INSERT INTO `wk_config` VALUES ('9', 'cfg_beian', '网站备案号：', '1', 'string', '', '');
INSERT INTO `wk_config` VALUES ('10', 'cfg_mb_open', '是否开启会员功能：', '2', 'radio', '0', '开启,关闭');
INSERT INTO `wk_config` VALUES ('11', 'cfg_mb_sendall', '是否开放会员对自定义模型投稿： ', '2', 'radio', '0', '开启,关闭');
INSERT INTO `wk_config` VALUES ('21', 'cfg_money_articledel', '取消审核通过扣除积分', '2', 'string', '2', '');
INSERT INTO `wk_config` VALUES ('13', 'cfg_mb_max', '会员附件总大小限制(MB)： ', '2', 'string', '500', '');
INSERT INTO `wk_config` VALUES ('14', 'cfg_mb_notallow', '不允许注册的会员id： ', '2', 'textarea', 'www,bbs,ftp,mail,user,users,admin,administrator', '');
INSERT INTO `wk_config` VALUES ('15', 'cfg_mb_idmin', '用户id最小长度：', '2', 'string', '3', '');
INSERT INTO `wk_config` VALUES ('16', 'cfg_mb_pwdmin', '用户密码最小长度： ', '2', 'string', '3', '');
INSERT INTO `wk_config` VALUES ('17', 'cfg_mb_spacesta', '会员使用权限开通状态', '2', 'radio', '0', '邮件验证,手工审核,无限制');
INSERT INTO `wk_config` VALUES ('24', 'cfg_adminemail', '网站发信EMAIL： ', '3', 'string', 'admin@pppon.com', '');
INSERT INTO `wk_config` VALUES ('18', 'cfg_md_mailtest', '是否限制Email只能注册一个帐号： ', '2', 'radio', '1', '是,否');
INSERT INTO `wk_config` VALUES ('19', 'cfg_money_reg', '注册赠送积分', '2', 'string', '10', '');
INSERT INTO `wk_config` VALUES ('12', 'cfg_mb_allowreg', '是否允许新会员注册： ', '2', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('20', 'cfg_money_articleadd', '成功发布文章赠送积分', '2', 'string', '2', '');
INSERT INTO `wk_config` VALUES ('22', 'cfg_cmspath', 'CMS安装目录： ', '3', 'string', '/pppon', '');
INSERT INTO `wk_config` VALUES ('23', 'cfg_cookie_encode', 'cookie加密码： ', '3', 'string', 'KcYQt2689M', '');
INSERT INTO `wk_config` VALUES ('26', 'cfg_list_symbol', '栏目位置的间隔符号： ', '3', 'string', ' > ', ' > ');
INSERT INTO `wk_config` VALUES ('27', 'cfg_smtp_server', 'smtp服务器： ', '3', 'string', 'smtp.126.com', 'smtp.qq.com');
INSERT INTO `wk_config` VALUES ('28', 'cfg_smtp_port', 'smtp服务器端口： ', '3', 'string', '25', '25');
INSERT INTO `wk_config` VALUES ('29', 'cfg_smtp_usermail', 'SMTP服务器的用户邮箱： ', '3', 'string', 'minglangasp@qq.com', 'minglangasp@qq.com');
INSERT INTO `wk_config` VALUES ('30', 'cfg_smtp_user', 'SMTP服务器的用户帐号： ', '3', 'string', 'pengyong881215', 'pppon');
INSERT INTO `wk_config` VALUES ('31', 'cfg_smtp_password', 'SMTP服务器的用户密码： ', '3', 'string', '123456', 'pppon');
INSERT INTO `wk_config` VALUES ('32', 'cfg_upload_switch', '删除文章文件同时删除相关附件文件：', '3', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('33', 'cfg_rewrite', '是否使用伪静态： ', '3', 'radio', '1', '是,否');
INSERT INTO `wk_config` VALUES ('34', 'cfg_delete', '文章回收站(是/否)开启：', '3', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('35', 'cfg_auot_description', '自动摘要长度（0-250，0表示不启用）： ', '4', 'string', '240', '240');
INSERT INTO `wk_config` VALUES ('36', 'cfg_rm_remote', '远程图片本地化： ', '4', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('37', 'cfg_arc_dellink', '删除非站内链接： ', '4', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('38', 'cfg_arc_autopic', '提取第一张图片作为缩略图：', '4', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('39', 'cfg_arc_autokeyword', '自动提取关键字： ', '4', 'radio', '1', '是,否');
INSERT INTO `wk_config` VALUES ('40', 'cfg_check_title', '发布文档时是否检测重复标题： ', '4', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('41', 'cfg_jump_once', '跳转网址是否直接跳转？（否则显示中转页）： ', '4', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('42', 'cfg_df_dutyadmin', '默认责任编辑(dutyadmin)： ', '4', 'string', 'admin', 'admin');
INSERT INTO `wk_config` VALUES ('43', 'cfg_arc_click', '文档默认点击数(-1表示随机50-200)： ', '4', 'string', '-1', '-1');
INSERT INTO `wk_config` VALUES ('44', 'cfg_arcautosp', '(是/否)开启长文章自动分页： ', '4', 'radio', '0', '是,否');
INSERT INTO `wk_config` VALUES ('45', 'cfg_arcautosp_size', '文章自动分页大小（单位: K）： ', '4', 'string', '5', '5');
INSERT INTO `wk_config` VALUES ('46', 'cfg_wap_tpl_default', 'wap网站默认模板', '1', 'string', 'default', '');
INSERT INTO `wk_config` VALUES ('47', 'cfg_mobile', '是否开通Wap访问(是:开启 否:关闭)', '3', 'radio', '1', '是,否');
INSERT INTO `wk_config` VALUES ('48', 'cfg_cmsswitch', '网站临时关闭选项(是:开启网站 否:关闭网站)', '1', 'radio', '1', '是,否');
INSERT INTO `wk_config` VALUES ('49', 'cfg_cmsswitch_msg', '网站临时关闭原因', '1', 'textarea', '网站临时关闭!', '');
TRUNCATE TABLE `wk_config_group`;
INSERT INTO `wk_config_group` VALUES ('1', '全局配置');
INSERT INTO `wk_config_group` VALUES ('2', '用户配置');
INSERT INTO `wk_config_group` VALUES ('3', '功能配置');
INSERT INTO `wk_config_group` VALUES ('4', '其它配置');
TRUNCATE TABLE `wk_friendlink`;
INSERT INTO `wk_friendlink` VALUES ('1', 'PPPON', 'http://www.pppon.com', '1359186731', '1', '1', './Public/Common/Images/logo.png');
TRUNCATE TABLE `wk_friendlink_group`;
INSERT INTO `wk_friendlink_group` VALUES ('1', '默认分类');
TRUNCATE TABLE `wk_member`;
INSERT INTO `wk_member` VALUES ('1', 'admin', 'c2d4101a4f67fbed957d260ff0f26a17', 'i@pengyong.info', '0', 'de90979d72b0d3b2cf4b3ccc0a3a632c', '1409499410', '1409499410', '127.0.0.1', '0', '23', '1', '山东', '济南', '634150845', '1988-01-23', '');
TRUNCATE TABLE `wk_member_msg`;
TRUNCATE TABLE `wk_member_rank`;
INSERT INTO `wk_member_rank` VALUES ('1', '工兵', '0', '01.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('2', '副班长', '10', '02.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('3', '正班长', '20', '03.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('4', '副排长', '30', '04.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('5', '排长', '50', '05.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('6', '副连长', '100', '06.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('7', '连长', '150', '07.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('8', '副营长', '220', '08.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('9', '营长', '350', '09.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('10', '副团长', '500', '10.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('11', '团长', '750', '11.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('12', '副旅长', '1000', '12.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('13', '旅长', '1550', '13.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('14', '副师长', '2150', '14.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('15', '师长', '3150', '15.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('16', '副军长', '5000', '16.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('17', '军长', '6350', '17.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('18', '副司令', '10000', '18.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('19', '司令', '12750', '19.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('20', '军委副主席', '15000', '20.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('21', '军委主席', '17500', '21.gif', '1');
INSERT INTO `wk_member_rank` VALUES ('22', 'vip', '0', 'vip.gif', '2');
INSERT INTO `wk_member_rank` VALUES ('23', '管理员', '0', '31.gif', '3');
TRUNCATE TABLE `wk_plugin`;
INSERT INTO `wk_plugin` VALUES ('1', '0', 'duoshuo', '多说评论插件', '将军', '歪酷CMS', '0');
INSERT INTO `wk_plugin` VALUES ('2', '0', 'guestbook', '歪酷留言本插件', '将军', '歪酷CMS', '0');
INSERT INTO `wk_plugin` VALUES ('3', '0', 'rss', '站点RSS订阅插件', '将军', '歪酷CMS', '0');
INSERT INTO `wk_plugin` VALUES ('4', '0', 'sitemap', '站点地图插件', '将军', '歪酷CMS', '0');
INSERT INTO `wk_plugin` VALUES ('5', '0', 'rewritehelper', '伪静态助手插件', '将军', '歪酷CMS', '0');
TRUNCATE TABLE `wk_special`;
TRUNCATE TABLE `wk_tags`;
TRUNCATE TABLE `wk_vote`;
INSERT INTO `wk_vote` VALUES ('1', '测试投票', '投票选项1=5\n投票选项2=5\n投票选项1=3\n投票选项2=4\n投票选项1=3\n投票选项2=4', '1', '1', '1358251426', '1359806677', '0');
INSERT INTO `wk_vote` VALUES ('2', '测试投票2', '投票选项1=5\n投票选项2=5\n投票选项1=3\n投票选项2=4\n投票选项1=3\n投票选项2=4', '1', '0', '1358251426', '1359806677', '0');
